mkdir -p ~/.vim/autoload ~/.vim/bundle 
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
git clone https://github.com/tpope/vim-sensible.git ~/.vim/bundle 
git clone https://github.com/fatih/vim-go.git ~/.vim/bundle  
git clone https://github.com/mileszs/ack.vim ~/.vim/bundle 
git clone https://github.com/kien/ctrlp.vim ~/.vim/bundle 
git clone https://github.com/gregsexton/gitv ~/.vim/bundle 
git clone https://github.com/Shougo/neocomplete.vim ~/.vim/bundle 
git clone https://github.com/scrooloose/nerdcommenter ~/.vim/bundle 
git clone https://github.com/scrooloose/syntastic ~/.vim/bundle 
git clone https://github.com/majutsushi/tagbar ~/.vim/bundle 
git clone https://github.com/tpope/vim-fugitive ~/.vim/bundle 
git clone https://github.com/airblade/vim-gitgutter ~/.vim/bundle 
ln -s ./vimrc ~/.vimrc
